interface Band
{
    band: string;
    albums: AlbumDetail[];
}

interface Track
{
    trackTitle: string;
    trackLength: string;
}

export interface AlbumDetail
{
    title: string;
    type: string;
    band: string;
    dateRecorded: Date;
    dateRelease: Date;
    studio: string;
    genre: string[];
    length: string;
    label: string;
    producer: string;
    imgCovername: string;
    tracks: Track[];
}

export const discography:Band[] =
[
    {
        band: "Devin Townsend",
        albums: [
            {
                title: "Punky Brüster – Cooked on Phonics",
                type: "studio",
                band: "Devin Townsend",
                dateRecorded: new Date(''),
                dateRelease: new Date('March 19, 1996'),
                studio: "",
                genre: ["Heavy metal","punk rock","pop punk","comedy rock"],
                length: "58:36",
                label: "Hevy Devy",
                producer: "Hevy Devy",
                imgCovername: "Punkybruster.jpg",
                tracks: [
                    { trackTitle: "Recipe for Bait", trackLength: "7:26"},
                    { trackTitle: "Fake Punk", trackLength: "2:21"},
                    { trackTitle: "EZ$$", trackLength: "4:13"},
                    { trackTitle: "Metal Dilemma", trackLength: "3:32"},
                    { trackTitle: "Oats Peas Beans & Barley", trackLength: "1:49"},
                    { trackTitle: "Wallet Chain", trackLength: "3:25"},
                    { trackTitle: "Heinous Anus", trackLength: "1:43"},
                    { trackTitle: "Heavy Metal Mama", trackLength: "4:47"},
                    { trackTitle: "Crusty's at the Ivanhoe", trackLength: "6:23"},
                    { trackTitle: "Picture of Myself", trackLength: "6:43"},
                    { trackTitle: "The Girls Next Door", trackLength: "4:28"},
                    { trackTitle: "Larry's O", trackLength: "6:06"},
                    { trackTitle: "Metal Heads Are Punk Rockers (Bonus track, cover/parody of «Sheena Is a Punk Rocker» by the Ramones)", trackLength: "3:06"},
                ],
            },
            {
                title: "Ocean Machine: Biomech",
                type: "studio",
                band: "Devin Townsend",
                dateRecorded: new Date('December 1996'),
                dateRelease: new Date('	July 21, 1997'),
                studio: "The Factory Studios and Slack Studios, Vancouver - S***hole Headquarters, Burnaby - Musibelios, Málaga",
                genre: ["Progressive metal","post-metal","hard rock","alternative metal","art rock"],
                length: "73:52",
                label: "HevyDevy (International edition), Sony Records (Japanese edition), USG Records and EastWest (German edition), InsideO0ut (2000 and 2010 re-issue)",
                producer: "Devin Townsend",
                imgCovername: "Biomech.jpg",
                tracks: [
                    { trackTitle: "Seventh Wave", trackLength: "6:50"},
                    { trackTitle: "Life", trackLength: "4:31"},
                    { trackTitle: "Night", trackLength: "4:45"},
                    { trackTitle: "Hide Nowhere", trackLength: "5:00"},
                    { trackTitle: "Sister", trackLength: "2:48"},
                    { trackTitle: "3 A.M.", trackLength: "1:56"},
                    { trackTitle: "Voices in the Fan", trackLength: "4:39"},
                    { trackTitle: "Greetings", trackLength: "2:53"},
                    { trackTitle: "Regulator", trackLength: "5:06"},
                    { trackTitle: "Funeral", trackLength: "8:06"},
                    { trackTitle: "Bastard", trackLength: "10:17"},
                    { trackTitle: "The Death of Music", trackLength: "12:15"},
                    { trackTitle: "Thing Beyond Things", trackLength: "4:47"},
                ],
            },
            {
                title: "Infinity",
                type: "studio",
                band: "Devin Townsend",
                dateRecorded: new Date('July 1998'),
                dateRelease: new Date('October 21, 1998'),
                studio: "Red Stripe Studios, Burnaby, BC, Canada - Premier, Coquitlam, BC, Canada",
                genre: ["Progressive metal","progressive rock","jazz fusion","experimental rock"],
                length: "46:41",
                label: "HevyDevy RecordsSony Records (Japanese edition)USG Records and EastWest (German edition)InsideOut (2000 and 2010 re-issue)",
                producer: "Devin Townsend",
                imgCovername: "Devin_Townsend_-_Infinity_-_album_cover.jpg",
                tracks: [
                    { trackTitle: "Truth", trackLength: "3:58"},
                    { trackTitle: "Christeen", trackLength: "3:41"},
                    { trackTitle: "Bad Devil", trackLength: "4:52"},
                    { trackTitle: "War", trackLength: "6:29"},
                    { trackTitle: 'Soul Driven (Soul Driven Cadillac)', trackLength: "5:14"},
                    { trackTitle: "Ants", trackLength: "2:01"},
                    { trackTitle: "Colonial Boy (Wild Colonial Boy)", trackLength: "3:04"},
                    { trackTitle: "Dynamics (Life Is All Dynamics)", trackLength: "5:08"},
                    { trackTitle: "Unity", trackLength: "6:07"},
                    { trackTitle: "Noisy Pink Bubbles", trackLength: "5:22"},
                    { trackTitle: "Sister (Live acoustic version)", trackLength: "2:15"},
                    { trackTitle: "Hide Nowhere (Live acoustic version)", trackLength: "5:03"},
                    { trackTitle: "Man ('96 Demo)", trackLength: "5:12"},
                ],
            },
            {
                title: "Physicist",
                type: "studio",
                band: "Devin Townsend",
                dateRecorded: new Date('March 2000'),
                dateRelease: new Date('June 26, 2000'),
                studio: "Hipposonic Studios, Vancouver, BC, Canada - Manland and Red Stripe Studio Burnaby, BC, Canada",
                genre: ["Progressive metal","thrash metal"],
                length: "46:34",
                label: "HevyDevy (International edition) SME Records (Japanese edition) InsideOut (German edition)",
                producer: "Devin Townsend",
                imgCovername: "Physicistcover.jpg",
                tracks: [
                    { trackTitle: "Namaste", trackLength: "3:34"},
                    { trackTitle: "Victim", trackLength: "3:15"},
                    { trackTitle: "Material", trackLength: "2:47"},
                    { trackTitle: "Kingdom", trackLength: "5:55"},
                    { trackTitle: "Death", trackLength: "2:27"},
                    { trackTitle: "Devoid", trackLength: "1:28"},
                    { trackTitle: "The Complex", trackLength: "3:31"},
                    { trackTitle: "Irish Maiden", trackLength: "2:45"},
                    { trackTitle: "Jupiter", trackLength: "3:36"},
                    { trackTitle: "Planet Rain", trackLength: "11:08"},
                    { trackTitle: "Forgotten (Hidden track)", trackLength: "5:59"},
                    { trackTitle: "Man (demo)", trackLength: "5:12"},
                    { trackTitle: "Ocean Machines (demo)", trackLength: "8:24"},
                    { trackTitle: "Promise (demo)", trackLength: "5:26"},
                ],
            },
            {
                title: "Terria",
                type: "studio",
                band: "Devin Townsend",
                dateRecorded: new Date('May 2001'),
                dateRelease: new Date('November 6, 2001'),
                studio: "Mushroom, Manland, Bedlam, Platinum Plus and Greenhouse Studios, Vancouver, BC",
                genre: ["Progressive metal","progressive rock","folk rock","experimental rock"],
                length: "71:54",
                label: "HevyDevy Records",
                producer: "Devin Townsend",
                imgCovername: "Terriacover.jpg",
                tracks: [
                    { trackTitle: "Olives", trackLength: "3:21"},
                    { trackTitle: "Mountain", trackLength: "6:32"},
                    { trackTitle: "Earth Day", trackLength: "9:35"},
                    { trackTitle: "Deep Peace", trackLength: "7:34"},
                    { trackTitle: "Canada", trackLength: "6:53"},
                    { trackTitle: "Down and Under", trackLength: "3:43"},
                    { trackTitle: "The Fluke", trackLength: "7:16"},
                    { trackTitle: "Nobody's Here", trackLength: "6:54"},
                    { trackTitle: "Tiny Tears", trackLength: "9:12"},
                    { trackTitle: "Stagnant", trackLength: "5:25"},
                    { trackTitle: "Humble (Hidden track)", trackLength: "5:30"},
                    { trackTitle: "Universal", trackLength: "5:55"},
                ],
            },
            {
                title: "Devlab",
                type: "studio",
                band: "Devin Townsend",
                dateRecorded: new Date('2004'),
                dateRelease: new Date('December 4, 2004'),
                studio: "Devlab",
                genre: ["Ambient","noise","experimental","drone"],
                length: "65:56",
                label: "HevyDevy Records",
                producer: "Devin Townsend",
                imgCovername: "Devlabcover.jpg",
                tracks: [
                    { trackTitle: "Devlab I", trackLength: "1:07"},
                    { trackTitle: "Devlab II", trackLength: "4:10"},
                    { trackTitle: "Devlab III", trackLength: "4:21"},
                    { trackTitle: "Devlab IV", trackLength: "2:42"},
                    { trackTitle: "Devlab V", trackLength: "5:08"},
                    { trackTitle: "Devlab VI", trackLength: "5:55"},
                    { trackTitle: "Devlab VII", trackLength: "1:42"},
                    { trackTitle: "Devlab VIII", trackLength: "4:30"},
                    { trackTitle: "Devlab IX", trackLength: "10:17"},
                    { trackTitle: "Devlab X", trackLength: "3:48"},
                    { trackTitle: "Devlab XI", trackLength: "1:35"},
                    { trackTitle: "Devlab XII", trackLength: "4:44"},
                    { trackTitle: "Devlab XIII", trackLength: "9:45"},
                    { trackTitle: "Devlab XIV", trackLength: "4:11"},
                    { trackTitle: "Devlab XV", trackLength: "2:04"},
                ],
            },
            {
                title: "The Hummer",
                type: "studio",
                band: "Devin Townsend",
                dateRecorded: new Date('_______'),
                dateRelease: new Date('November 15, 2006'),
                studio: "",
                genre: ["Ambient","noise"],
                length: "73:24",
                label: "HevyDevy",
                producer: "Devin Townsend",
                imgCovername: "The_Hummer.jpg",
                tracks: [
                    { trackTitle: "The Hummer", trackLength: "15:55"},
                    { trackTitle: "Arc", trackLength: "23:04"},
                    { trackTitle: "Consciousness Causes Collapse", trackLength: "6:39"},
                    { trackTitle: "Equation", trackLength: "3:16"},
                    { trackTitle: "The Abacus", trackLength: "8:03"},
                    { trackTitle: "Cosmic Surf", trackLength: "16:27"},
                ],
            },  
            {
                title: "Ziltoid the Omniscient",
                type: "studio",
                band: "Devin Townsend",
                dateRecorded: new Date('March 1, 2007'),
                dateRelease: new Date('May 21, 2007'),
                studio: `Townsend's home studio, the "Devlab" (Pitt Meadows, BC)`,
                genre: ["Progressive metal","comedy rock","experimental metal","extreme metal"],
                length: "53:46",
                label: "HevyDevy",
                producer: "Devin Townsend",
                imgCovername: "Ziltoidtheomniscientcover.jpg",
                tracks: [
                    { trackTitle: "ZTO", trackLength: "1:17"},
                    { trackTitle: "By Your Command", trackLength: "8:09"},
                    { trackTitle: "Ziltoidia Attaxx!!!", trackLength: "3:42"},
                    { trackTitle: "Solar Winds", trackLength: "9:46"},
                    { trackTitle: "Hyperdrive", trackLength: "3:47"},
                    { trackTitle: "N9", trackLength: "5:30"},
                    { trackTitle: "Planet Smasher", trackLength: "5:45"},
                    { trackTitle: "Omnidimensional Creator", trackLength: "0:48"},
                    { trackTitle: "Color Your World", trackLength: "9:44"},
                    { trackTitle: "The Greys", trackLength: "4:15"},
                    { trackTitle: "Tall Latte", trackLength: "1:03"},
                    { trackTitle: "Don't Know Why (aka Messages from Ziltoid)", trackLength: "7:34"},
                    { trackTitle: "Travelling Salesman", trackLength: "2:14"},
                    { trackTitle: "Another Road", trackLength: "4:29"},
                ],
            },
            {
                title: "Empath",
                type: "studio",
                band: "Devin Townsend",
                dateRecorded: new Date('2018'),
                dateRelease: new Date('March 29, 2019'),
                studio: "Monnow Valley Studios, Rockfield, Wales, UK - The Armoury Studios, The Farm, Devlab, and The Armory, Vancouver, Canada - The Grid, Montreal, Canada",
                genre: ["Progressive metal","progressive rock"],
                length: "74:08",
                label: "Inside Out, HevyDevy",
                producer: "Devin Townsend",
                imgCovername: "Devin_Townsend_Empath_cover.jpg",
                tracks: [
                    { trackTitle: "Castaway", trackLength: "2:28"},
                    { trackTitle: "Genesis", trackLength: "6:05"},
                    { trackTitle: "Spirits Will Collide", trackLength: "4:39"},
                    { trackTitle: "Evermore", trackLength: "5:30"},
                    { trackTitle: "Sprite", trackLength: "6:37"},
                    { trackTitle: "Hear Me", trackLength: "6:30"},
                    { trackTitle: "Why?", trackLength: "4:59"},
                    { trackTitle: "Borderlands", trackLength: "11:02"},
                    { trackTitle: "Requiem", trackLength: "2:46"},
                    { trackTitle: "Singularity", trackLength: "23:33"},
                ],
            },     
            {
                title: "The Puzzle",
                type: "studio",
                band: "Devin Townsend",
                dateRecorded: new Date('2021'),
                dateRelease: new Date('December 3, 2021'),
                studio: "The Armoury Studios, The Farm, Devlab, and The Armory, Vancouver, Canada",
                genre: ["Ambient","experimental"],
                length: "65:17",
                label: "HevyDevy",
                producer: "Devin Townsend",
                imgCovername: "Devin_Townsend_-_The_Puzzle.jpg",
                tracks: [
                    { trackTitle: "Chromatic Ridge", trackLength: "3:43"},
                    { trackTitle: "Life Is but a Dream", trackLength: "3:29"},
                    { trackTitle: "Yucky Lung", trackLength: "1:22"},
                    { trackTitle: "Kittenhead", trackLength: "1:13"},
                    { trackTitle: "Shark in the Ice", trackLength: "1:49"},
                    { trackTitle: "Devil in the Details", trackLength: "0:58"},
                    { trackTitle: "Hammerhead Sugarplum", trackLength: "3:47"},
                    { trackTitle: "Me and the Moon", trackLength: "4:12"},
                    { trackTitle: "Anxiety in Pyjamas", trackLength: "3:28"},
                    { trackTitle: "The Yugas", trackLength: "3:01"},
                    { trackTitle: "Albert Hall", trackLength: "3:58"},
                    { trackTitle: "StarChasm", trackLength: "3:59"},
                    { trackTitle: "Perfect Owl", trackLength: "2:17"},
                    { trackTitle: "Maybe over the Void", trackLength: "2:56"},
                    { trackTitle: "Light Year Whale", trackLength: "4:31"},
                    { trackTitle: "FrogFlowers", trackLength: "1:11"},
                    { trackTitle: "Mother", trackLength: "4:28"},
                    { trackTitle: "Southern Sky Geometry", trackLength: "2:11"},
                    { trackTitle: "The Puzzle", trackLength: "5:22"},
                    { trackTitle: "Monuments of Glitch", trackLength: "7:22"},
                ],
            },
            {
                title: "Snuggles",
                type: "studio",
                band: "Devin Townsend",
                dateRecorded: new Date('2021'),
                dateRelease: new Date('December 3, 2021'),
                studio: "The Armoury Studios, The Farm, Devlab, and The Armory, Vancouver, Canada",
                genre: ["Ambient","experimental"],
                length: "38:32",
                label: "HevyDevy",
                producer: "Devin Townsend",
                imgCovername: "Devin_Townsend_-_Snuggles.jpg",
                tracks: [
                    { trackTitle: "Beyond Measure", trackLength: "1:31"},
                    { trackTitle: "Blue Dot", trackLength: "3:07"},
                    { trackTitle: "Drifting and Dreaming", trackLength: "4:26"},
                    { trackTitle: "Sundance", trackLength: "0:53"},
                    { trackTitle: "Minds Are Changing", trackLength: "3:46"},
                    { trackTitle: "The Ocean", trackLength: "4:54"},
                    { trackTitle: "Distant, Elegant", trackLength: "3:34"},
                    { trackTitle: "Replikiss", trackLength: "3:33"},
                    { trackTitle: "I Agree", trackLength: "3:23"},
                    { trackTitle: "Tryst", trackLength: "3:30"},
                    { trackTitle: "Sunset Rump", trackLength: "1:32"},
                    { trackTitle: "The Option", trackLength: "4:23"},
                ],
            },
        ]
    },
    {
        band: "Devin Townsend Project",
        albums: [
            {
                title: "Ki",
                type: "studio",
                band: "Devin Townsend Project",
                dateRecorded: new Date('2009'),
                dateRelease: new Date('May 25, 2009'),
                studio: "Devestate, Studio D, and the Factory",
                genre: ["Progressive rock","blues rock","progressive metal","art rock"],
                length: "66:50",
                label: "HevyDevy",
                producer: "Devin Townsend",
                imgCovername: "Devin_townsend_ki.jpg",
                tracks: [
                    { trackTitle: "A Monday", trackLength: "1:43"},
                    { trackTitle: "Coast", trackLength: "4:36"},
                    { trackTitle: "Disruptr", trackLength: "5:49"},
                    { trackTitle: "Gato", trackLength: "5:23"},
                    { trackTitle: "Terminal", trackLength: "6:58"},
                    { trackTitle: "Heaven's End", trackLength: "8:54"},
                    { trackTitle: "Ain't Never Gonna Win", trackLength: "3:17"},
                    { trackTitle: "Winter", trackLength: "4:48"},
                    { trackTitle: "Trainfire", trackLength: "5:59"},
                    { trackTitle: "Lady Helen", trackLength: "6:05"},
                    { trackTitle: "Ki", trackLength: "7:21"},
                    { trackTitle: "Quiet Riot", trackLength: "3:02"},
                    { trackTitle: "Demon League", trackLength: "2:55"},
                ],
            },
            {
                title: "Addicted",
                type: "studio",
                band: "Devin Townsend Project",
                dateRecorded: new Date('September 8, 2009'),
                dateRelease: new Date('November 17, 2009'),
                studio: "",
                genre: ["Alternative rock","hard rock","progressive metal"],
                length: "46:49",
                label: "HevyDevy, InsideOut Music",
                producer: "Devin Townsend",
                imgCovername: "The_Devin_Townsend_Project_-_Addicted_(2009).jpg",
                tracks: [
                    { trackTitle: "Addicted!", trackLength: "5:37"},
                    { trackTitle: "Universe in a Ball!", trackLength: "4:09"},
                    { trackTitle: "Bend It Like Bender!", trackLength: "3:37"},
                    { trackTitle: "Supercrush!", trackLength: "5:13"},
                    { trackTitle: "Hyperdrive!", trackLength: "3:36"},
                    { trackTitle: "Resolve!", trackLength: "3:12"},
                    { trackTitle: "Ih-Ah!", trackLength: "3:45"},
                    { trackTitle: "The Way Home!", trackLength: "3:14"},
                    { trackTitle: "Numbered!", trackLength: "4:55"},
                    { trackTitle: "Awake!!", trackLength: "9:44"},
                ],
            },
            
            {
                title: "Deconstruction",
                type: "studio",
                band: "Devin Townsend Project",
                dateRecorded: new Date('February 2011'),
                dateRelease: new Date('June 20, 2011'),
                studio: "",
                genre: ["Progressive metal","symphonic metal","extreme metal","avant-garde metal"],
                length: "70:39",
                label: "HevyDevy, InsideOut Music",
                producer: "Devin Townsend",
                imgCovername: "Deconstruction_(The_Devin_Townsend_Project_album)_cover.jpg",
                tracks: [
                    { trackTitle: "Praise the Lowered", trackLength: "	6:02"},
                    { trackTitle: "Stand", trackLength: "9:36"},
                    { trackTitle: "Juular", trackLength: "3:46"},
                    { trackTitle: "Planet of the Apes", trackLength: "10:59"},
                    { trackTitle: "Sumeria", trackLength: "6:37"},
                    { trackTitle: "The Mighty Masturbator", trackLength: "16:28"},
                    { trackTitle: "Pandemic", trackLength: "3:29"},
                    { trackTitle: "Deconstruction", trackLength: "9:27"},
                    { trackTitle: "Poltergeist", trackLength: "4:25"},
                    { trackTitle: "Ho Krll", trackLength: "5:58"},
                ],
            },
            
            {
                title: "Ghost",
                type: "studio",
                band: "Devin Townsend Project",
                dateRecorded: new Date('2010'),
                dateRelease: new Date('June 20, 2011'),
                studio: "The Factory and The S*** Shack",
                genre: ["Progressive rock","ambient","folk rock","post-rock"],
                length: "72:45",
                label: "HevyDevy, Inside Out",
                producer: "Devin Townsend",
                imgCovername: "Ghost_(The_Devin_Townsend_Project_album)_cover.jpg",
                tracks: [
                    { trackTitle: "Fly", trackLength: "4:15"},
                    { trackTitle: "Heart Baby", trackLength: "5:55"},
                    { trackTitle: "Feather", trackLength: "11:30"},
                    { trackTitle: "Kawaii", trackLength: "2:52"},
                    { trackTitle: "Ghost", trackLength: "6:24"},
                    { trackTitle: "Blackberry", trackLength: "4:53"},
                    { trackTitle: "Monsoon", trackLength: "4:37"},
                    { trackTitle: "Dark Matters", trackLength: "1:57"},
                    { trackTitle: "Texada", trackLength: "9:30"},
                    { trackTitle: "Seams", trackLength: "4:04"},
                    { trackTitle: "Infinite Ocean", trackLength: "8:01"},
                    { trackTitle: "As You Were", trackLength: "8:47"},
                    { trackTitle: "Radial Highway (iTunes exclusive bonus track)", trackLength: "6:49"},
                ],
            },
            
            {
                title: "Epicloud",
                type: "studio",
                band: "Devin Townsend Project",
                dateRecorded: new Date('May 2012'),
                dateRelease: new Date('September 18, 2012'),
                studio: "Kingdom Studio (Perth, Australia), Strait Sound Studio (Gibsons, Canada), The Armoury Studios (Vancouver, Canada)",
                genre: ["Alternative rock","hard rock","progressive metal"],
                length: "49:52",
                label: "HevyDevy",
                producer: "Devin Townsend",
                imgCovername: "Epicloud_album_cover.jpg",
                tracks: [
                    { trackTitle: "Effervescent!", trackLength: "0:44"},
                    { trackTitle: "True North", trackLength: "3:53"},
                    { trackTitle: "Lucky Animals", trackLength: "3:21"},
                    { trackTitle: "Liberation", trackLength: "3:21"},
                    { trackTitle: "Where We Belong", trackLength: "4:27"},
                    { trackTitle: "Save Our Now", trackLength: "4:08"},
                    { trackTitle: "Kingdom", trackLength: "5:29"},
                    { trackTitle: "Divine", trackLength: "3:17"},
                    { trackTitle: "Grace", trackLength: "6:09"},
                    { trackTitle: "More!", trackLength: "4:05"},
                    { trackTitle: "Lessons", trackLength: "1:07"},
                    { trackTitle: "Hold On", trackLength: "3:57"},
                    { trackTitle: "Angel", trackLength: "5:54"},
                    { trackTitle: "Epicloud (vinyl bonus track)", trackLength: "6:07"},
                    { trackTitle: "Cry Forever (iTunes bonus track)", trackLength: "4:00"},
                    { trackTitle: "Take My Ego (iTunes bonus track)", trackLength: "6:22"},
                ],
            },
            
            {
                title: "Casualties of Cool",
                type: "studio",
                band: "Devin Townsend Project",
                dateRecorded: new Date('February 2014'),
                dateRelease: new Date('May 14, 2014'),
                studio: "",
                genre: ["Country rock","blues rock","chamber rock","ambient","alternative country"],
                length: "73:47",
                label: "HevyDevy",
                producer: "Devin Townsend",
                imgCovername: "Casualties_of_Cool.jpg",
                tracks: [
                    { trackTitle: "Daddy", trackLength: "5:11"},
                    { trackTitle: "Mountaintop", trackLength: "5:33"},
                    { trackTitle: "Flight", trackLength: "5:32"},
                    { trackTitle: "The Code", trackLength: "4:41"},
                    { trackTitle: "Moon", trackLength: "6:28"},
                    { trackTitle: "Pier", trackLength: "3:39"},
                    { trackTitle: "Ether", trackLength: "4:50"},
                    { trackTitle: "Hejda", trackLength: "3:40"},
                    { trackTitle: "Forgive Me", trackLength: "6:00"},
                    { trackTitle: "Broken", trackLength: "1:59"},
                    { trackTitle: "Bones", trackLength: "3:39"},
                    { trackTitle: "Deathscope", trackLength: "6:13"},
                    { trackTitle: "The Field", trackLength: "4:01"},
                    { trackTitle: "The Bridge", trackLength: "8:13"},
                    { trackTitle: "Pure", trackLength: "4:08"},
                ],
            },
            
            {
                title: "Z² (Sky Blue)",
                type: "studio",
                band: "Devin Townsend Project",
                dateRecorded: new Date('May 2014'),
                dateRelease: new Date('	October 27, 2014'),
                studio: "",
                genre: ["Progressive metal","progressive rock","experimental rock","new-age"],
                length: "56:32",
                label: "HevyDevy",
                producer: "Devin Townsend",
                imgCovername: "Sky_Blue_(Album_Cover).jpg",
                tracks: [
                    { trackTitle: "Rejoice", trackLength: "4:16"},
                    { trackTitle: "Fallout", trackLength: "4:30"},
                    { trackTitle: "Midnight Sun", trackLength: "4:58"},
                    { trackTitle: "A New Reign", trackLength: "4:52"},
                    { trackTitle: "Universal Flame", trackLength: "4:39"},
                    { trackTitle: "Warrior", trackLength: "3:31"},
                    { trackTitle: "Sky Blue", trackLength: "3:52"},
                    { trackTitle: "Silent Militia", trackLength: "4:28"},
                    { trackTitle: "Rain City", trackLength: "7:45"},
                    { trackTitle: "Forever", trackLength: "3:45"},
                    { trackTitle: "Before We Die", trackLength: "8:24"},
                    { trackTitle: "The Ones Who Love", trackLength: "1:32"},
                ],
            },
            
            {
                title: "Z² (Dark Matters)",
                type: "studio",
                band: "Devin Townsend Project",
                dateRecorded: new Date('May 2014'),
                dateRelease: new Date('	October 27, 2014'),
                studio: "",
                genre: ["Progressive metal","experimental metal","industrial metal"],
                length: "53:23",
                label: "HevyDevy",
                producer: "Devin Townsend",
                imgCovername: "Dark_Matters_(Album_Cover).jpg",
                tracks: [
                    { trackTitle: "Z²", trackLength: "3:59"},
                    { trackTitle: "From Sleep Awake", trackLength: "3:00"},
                    { trackTitle: "Ziltoidian Empire", trackLength: "6:26"},
                    { trackTitle: "War Princess", trackLength: "8:18"},
                    { trackTitle: "Deathray", trackLength: "4:43"},
                    { trackTitle: "March of the Poozers", trackLength: "6:25"},
                    { trackTitle: "Wandering Eye", trackLength: "3:41"},
                    { trackTitle: "Earth", trackLength: "7:39"},
                    { trackTitle: "Ziltoid Goes Home", trackLength: "6:20"},
                    { trackTitle: "Through the Wormhole", trackLength: "3:44"},
                    { trackTitle: "Dimension Z", trackLength: "6:13"},
                ],
            },
            
            {
                title: "Transcendence",
                type: "studio",
                band: "Devin Townsend Project",
                dateRecorded: new Date('May 2016'),
                dateRelease: new Date('September 9, 2016'),
                studio: "Armoury Studios",
                genre: ["Progressive metal","symphonic metal"],
                length: "64:16",
                label: "HevyDevy",
                producer: `Devin Townsend & Adam "Nolly" Getgood`,
                imgCovername: "Devin_Townsend_Project_-_Transcendence_2016.jpg",
                tracks: [
                    { trackTitle: "Truth", trackLength: "4:47"},
                    { trackTitle: "Stormbending", trackLength: "5:22"},
                    { trackTitle: "Failure", trackLength: "6:02"},
                    { trackTitle: "Secret Sciences", trackLength: "7:28"},
                    { trackTitle: "Higher", trackLength: "9:40"},
                    { trackTitle: "Stars", trackLength: "4:17"},
                    { trackTitle: "Transcendence", trackLength: "5:54"},
                    { trackTitle: "Offer Your Light", trackLength: "3:57"},
                    { trackTitle: "From the Heart", trackLength: "8:23"},
                    { trackTitle: "Transdermal Celebration (Ween cover)", trackLength: "8:26"},
                ],
            },
            
            {
                title: "By a Thread: Live in London 2011",
                type: "live",
                band: "Devin Townsend Project",
                dateRecorded: new Date('November 2011'),
                dateRelease: new Date('	June 18, 2012'),
                studio: "",
                genre: ["Progressive metal","industrial metal","extreme metal","alternative metal","progressive rock","ambient","new-age"],
                length: "",
                label: "HevyDevy",
                producer: "Devin Townsend",
                imgCovername: "DTP_Live_in_London_2011.jpg",
                tracks: [
                    { trackTitle: "A Monday", trackLength: ""},
                    { trackTitle: "Coast", trackLength: ""},
                    { trackTitle: "Disruptr", trackLength: ""},
                    { trackTitle: "Gato", trackLength: ""},
                    { trackTitle: "Terminal", trackLength: ""},
                    { trackTitle: "Heaven's End", trackLength: ""},
                    { trackTitle: "Ain't Never Gonna Win", trackLength: ""},
                    { trackTitle: "Winter", trackLength: ""},
                    { trackTitle: "Trainfire", trackLength: ""},
                    { trackTitle: "Lady Helen", trackLength: ""},
                    { trackTitle: "Ki", trackLength: ""},
                    { trackTitle: "Quiet Riot", trackLength: ""},
                    { trackTitle: "Demon League", trackLength: ""},
                    { trackTitle: "Addicted!", trackLength: ""},
                    { trackTitle: "Universe in a Ball!", trackLength: ""},
                    { trackTitle: "Bend It Like Bender!", trackLength: ""},
                    { trackTitle: "Supercrush!", trackLength: ""},
                    { trackTitle: "Hyperdrive!", trackLength: ""},
                    { trackTitle: "Resolve!", trackLength: ""},
                    { trackTitle: "Ih-Ah!", trackLength: ""},
                    { trackTitle: "The Way Home!", trackLength: ""},
                    { trackTitle: "Numbered!", trackLength: ""},
                    { trackTitle: "Awake!!", trackLength: ""},
                    { trackTitle: "Praise the Lowered", trackLength: ""},
                    { trackTitle: "Stand", trackLength: ""},
                    { trackTitle: "Juular", trackLength: ""},
                    { trackTitle: "Planet of the Apes", trackLength: ""},
                    { trackTitle: "Sumeria", trackLength: ""},
                    { trackTitle: "The Mighty Masturbator", trackLength: ""},
                    { trackTitle: "Pandemic", trackLength: ""},
                    { trackTitle: "Deconstruction", trackLength: ""},
                    { trackTitle: "Poltergeist", trackLength: ""},
                    { trackTitle: "Ho Krll", trackLength: ""},
                    { trackTitle: "Fly", trackLength: ""},
                    { trackTitle: "Heart Baby", trackLength: ""},
                    { trackTitle: "Feather", trackLength: ""},
                    { trackTitle: "Kawaii", trackLength: ""},
                    { trackTitle: "Ghost", trackLength: ""},
                    { trackTitle: "Blackberry", trackLength: ""},
                    { trackTitle: "Monsoon", trackLength: ""},
                    { trackTitle: "Dark Matters", trackLength: ""},
                    { trackTitle: "Texada", trackLength: ""},
                    { trackTitle: "Seams", trackLength: ""},
                    { trackTitle: "Infinite Ocean", trackLength: ""},
                    { trackTitle: "As You Were", trackLength: ""},
                    { trackTitle: "Radial Highway (iTunes exclusive bonus track)", trackLength: ""},
                ],
            }
        ],
    },
    {
        band: "The Devin Townsend Band",
        albums:[
            {
                title: "Accelerated Evolution",
                type: "studio",
                band: "The Devin Townsend Band",
                dateRecorded: new Date('November 2002'),
                dateRelease: new Date('March 31, 2003'),
                studio: "The Armoury, Merchland and Hipposonic studios, Vancouver, Canada",
                genre: ["Progressive metal","hard rock","alternative rock"],
                length: "54:30",
                label: "HevyDevy",
                producer: "Devin Townsend",
                imgCovername: "Devin_Townsend_Accelerated_Evolution_cover.jpg",
                tracks: [
                    { trackTitle: "Depth Charge", trackLength: "6:04"},
                    { trackTitle: "Storm", trackLength: "4:39"},
                    { trackTitle: "Random Analysis", trackLength: "5:59"},
                    { trackTitle: "Deadhead", trackLength: "8:05"},
                    { trackTitle: "Suicide", trackLength: "6:45"},
                    { trackTitle: "Traveller", trackLength: "4:13"},
                    { trackTitle: "Away", trackLength: "7:49"},
                    { trackTitle: "Sunday Afternoon", trackLength: "6:20"},
                    { trackTitle: "Slow Me Down", trackLength: "4:35"},
                ],
            },
            {
                title: "Synchestra",
                type: "studio",
                band: "The Devin Townsend Band",
                dateRecorded: new Date('2005'),
                dateRelease: new Date('January 31, 2006'),
                studio: "Devlab, Armoury Studios, and Hipposonic",
                genre: ["Progressive metal","progressive rock","hard rock","heavy metal"],
                length: "65:20",
                label: "HevyDevy",
                producer: "Devin Townsend",
                imgCovername: "The_Devin_Townsend_Band_-_Synchestra.jpg",
                tracks: [
                    { trackTitle: "Let It Roll", trackLength: "2:52"},
                    { trackTitle: "Hypergeek", trackLength: "2:20"},
                    { trackTitle: "Triumph", trackLength: "7:08"},
                    { trackTitle: "Babysong", trackLength: "5:30"},
                    { trackTitle: "Vampolka", trackLength: "1:36"},
                    { trackTitle: "Vampira", trackLength: "3:27"},
                    { trackTitle: "Mental Tan", trackLength: "2:15"},
                    { trackTitle: "Gaia", trackLength: "6:03"},
                    { trackTitle: "Pixillate", trackLength: "8:17"},
                    { trackTitle: "Judgement", trackLength: "5:55"},
                    { trackTitle: "A Simple Lullaby", trackLength: "7:09"},
                    { trackTitle: "Sunset", trackLength: "2:31"},
                    { trackTitle: "Notes from Africa", trackLength: "7:42"},
                    { trackTitle: "Sunshine and Happiness (hidden track)", trackLength: "2:35"},
                ],
            },
        ],
    },
    {
        band: "Strapping Young Lad",
        albums:[
            {
                title: "Heavy As A Really Heavy Thing",
                type: "studio",
                band: "Strapping Young Lad",
                dateRecorded: new Date('December 1994'),
                dateRelease: new Date('April 4, 1995'),
                studio: "Mushroom Studios (Vancouver, Canada), Greenhouse Studios (Vancouver, Canada)",
                genre: ["Industrial metal","extreme metal","thrash metal"],
                length: "39:48",
                label: "Century Media",
                producer: "Devin Townsend",
                imgCovername: "Strappingyoungladhaarht.jpg",
                tracks: [
                            { trackTitle: "S.Y.L", trackLength: "4:47"},
                            { trackTitle: "In the Rainy Season", trackLength: "4:37"},
                            { trackTitle: "Goat", trackLength: "3:30"},
                            { trackTitle: "Cod Metal King", trackLength: "5:08"},
                            { trackTitle: "Happy Camper (Carpe B.U.M.)", trackLength: "3:00"},
                            { trackTitle: "Critic", trackLength: "4:07"},
                            { trackTitle: "The Filler – Sweet City Jesus", trackLength: "5:24"},
                            { trackTitle: "Skin Me", trackLength: "3:29"},
                            { trackTitle: "Drizzlehell", trackLength: "3:09"},
                            { trackTitle: "Satan's Ice Cream Truck", trackLength: "2:33"},
                            { trackTitle: "Japan (Japanese and 2006 reissue bonus track)", trackLength: "5:18"},
                            { trackTitle: "Monday (2006 reissue bonus track)", trackLength: "5:14"},
                            { trackTitle: "Exciter (Judas Priest cover; European and 2006 reissue bonus track)", trackLength: "6:04"},
                        ],
            },
            {
                title: "City",
                type: "studio",
                band: "Strapping Young Lad",
                dateRecorded: new Date('July 1996'),
                dateRelease: new Date('February 11, 1997'),
                studio: "Red Stripe Studio, Burnaby Mothership Studios, Los Angeles, California",
                genre: ["Industrial metal","extreme metal","thrash metal"],
                length: "39:22",
                label: "Century Media",
                producer: "Devin Townsend & Daniel Bergstrand",
                imgCovername: "Strappingyoungladcity.jpg",
                tracks: [
                    { trackTitle: "Velvet Kevorkian", trackLength: "1:17"},
                    { trackTitle: "All Hail the New Flesh", trackLength: "5:24"},
                    { trackTitle: "Oh My ******* God", trackLength: "3:34"},
                    { trackTitle: "Detox", trackLength: "5:37"},
                    { trackTitle: "Home Nucleonics", trackLength: "2:31"},
                    { trackTitle: "AAA", trackLength: "5:21"},
                    { trackTitle: "Underneath the Waves", trackLength: "3:40"},
                    { trackTitle: "Room 429 (Tod Ashley) (Cop Shoot Cop cover)", trackLength: "5:21"},
                    { trackTitle: "Spirituality", trackLength: "6:34"},
                    { trackTitle: "Centipede (available on Japanese release and 2007 remaster)", trackLength: "7:55"},
                    { trackTitle: "Home Nucleonics ('96 demo, available on Japanese release of No Sleep 'till Bedtime and 2007 remaster)", trackLength: "3:02"},
                    { trackTitle: "Headrhoid (Gunt demo, available on Japanese release of No Sleep 'till Bedtime and 2007 remaster)", trackLength: "1:38"},
                    { trackTitle: "Detox ('96 demo, available on Japanese release of No Sleep 'till Bedtime and 2007 remaster)", trackLength: "5:48"},
                    { trackTitle: "AAA ('96 demo, available on Japanese release of No Sleep 'till Bedtime and 2007 remaster)", trackLength: "5:22"},
                ],
            },
            {
                title: "Strapping Young Lad",
                type: "studio",
                band: "Strapping Young Lad",
                dateRecorded: new Date('February 11, 2003'),
                dateRelease: new Date('October 2002'),
                studio: "Armoury, Hipposonic and Diamond Sharp Studios (Vancouver, Canada)",
                genre: ["Thrash metal","death metal","groove metal"],
                length: "39:01",
                label: "Century Media",
                producer: "Strapping Young Lad",
                imgCovername: "Strappingyoungladsyl.jpg",
                tracks: [
                    { trackTitle: "Dire", trackLength: "1:10"},
                    { trackTitle: "Consequence", trackLength: "4:02"},
                    { trackTitle: "Relentless", trackLength: "3:03"},
                    { trackTitle: "Rape Song", trackLength: "3:09"},
                    { trackTitle: "Aftermath", trackLength: "6:46"},
                    { trackTitle: "Devour", trackLength: "2:53"},
                    { trackTitle: "Last Minute", trackLength: "3:58"},
                    { trackTitle: "Force Fed", trackLength: "5:23"},
                    { trackTitle: "Dirt Pride", trackLength: "2:40"},
                    { trackTitle: "Bring On the Young", trackLength: "5:53"},
                    { trackTitle: "Detox (live, only available on Australian release)", trackLength: "6:40"},
                    { trackTitle: "Underneath the Waves (live, only available on Japanese release)", trackLength: "4:00"},
                ],
            },
            {
                title: "Alien",
                type: "studio",
                band: "Strapping Young Lad",
                dateRecorded: new Date('November 2004'),
                dateRelease: new Date('March 22, 2005'),
                studio: "The Armoury (Vancouver, British Columbia, Canada)",
                genre: ["Extreme metal","industrial metal","thrash metal","black metal"],
                length: "54:45",
                label: "Hevy Devy, Century Media",
                producer: "	Devin Townsend, Strapping Young Lad",
                imgCovername: "Strappingyoungladalien.jpg",
                tracks: [
                    { trackTitle: "Imperial", trackLength: "2:17"},
                    { trackTitle: "Skeksis", trackLength: "6:42"},
                    { trackTitle: "S***storm", trackLength: "4:22"},
                    { trackTitle: "Love?", trackLength: "4:53"},
                    { trackTitle: "Shine", trackLength: "5:13"},
                    { trackTitle: "We Ride", trackLength: "2:37"},
                    { trackTitle: "Possessions", trackLength: "4:12"},
                    { trackTitle: "Two Weeks", trackLength: "3:28"},
                    { trackTitle: "Thalamus", trackLength: "3:58"},
                    { trackTitle: "Zen", trackLength: "5:02"},
                    { trackTitle: "Info Dump", trackLength: "11:56"},
                    { trackTitle: "Zodiac (Melvins cover)", trackLength: "3:59"},
                    { trackTitle: "Love? (Extended version)", trackLength: "5:43"},
                    { trackTitle: "In the Rainy Season (Live)", trackLength: "5:29"},
                ],
            },
            {
                title: "The New Black",
                type: "studio",
                band: "Strapping Young Lad",
                dateRecorded: new Date('2006'),
                dateRelease: new Date('July 11, 2006'),
                studio: "",
                genre: ["Extreme metal","industrial metal","progressive metal"],
                length: "42:43",
                label: "Century Media",
                producer: "Devin Townsend, Strapping Young Lad",
                imgCovername: "Syl-newblack.jpg",
                tracks: [
                    { trackTitle: "Decimator", trackLength: "2:53"},
                    { trackTitle: "You Suck (featuring Cam Kroetsch)", trackLength: "2:40"},
                    { trackTitle: "Anti-Product", trackLength: "3:56"},
                    { trackTitle: "Monument", trackLength: "4:11"},
                    { trackTitle: "Wrong Side", trackLength: "3:35"},
                    { trackTitle: "Hope", trackLength: "5:02"},
                    { trackTitle: "Far Beyond Metal (featuring Oderus Urungus)", trackLength: "4:36"},
                    { trackTitle: "F****r (featuring Bif Naked)", trackLength: "3:53"},
                    { trackTitle: "Almost Again", trackLength: "3:43"},
                    { trackTitle: "Polyphony", trackLength: "1:54"},
                    { trackTitle: "The New Black", trackLength: "6:15"},
                    { trackTitle: "The Long Pig", trackLength: "1:22"},
                    { trackTitle: "Zodiac (Melvins cover)", trackLength: "3:59"},   
                ],
            },
            {
                title: "No Sleep 'till Bedtime",
                type: "live",
                band: "Strapping Young Lad",
                dateRecorded: new Date('October 12, 1997'),
                dateRelease: new Date('June 2, 1998'),
                studio: "",
                genre: ["Extreme metal","industrial metal"],
                length: "42:32",
                label: "Century Media",
                producer: "Devin Townsend",
                imgCovername: "Strapping_Young_Lad_-_No_Sleep_Till_Bedtime.jpg",
                tracks: [
                    { trackTitle: "Velvet Kevorkian", trackLength: "2:42"},
                    { trackTitle: "All Hail the New Flesh", trackLength: "5:24"},
                    { trackTitle: "Home Nucleonics", trackLength: "2:24"},
                    { trackTitle: "Oh My Fucking God", trackLength: "3:40"},
                    { trackTitle: "S.Y.L.", trackLength: "4:53"},
                    { trackTitle: "In the Rainy Season", trackLength: "5:29"},
                    { trackTitle: "Far Beyond Metal", trackLength: "4:46"},
                    { trackTitle: "Japan", trackLength: "5:17"},
                    { trackTitle: "Centipede", trackLength: "7:55"},
                    { trackTitle: "Home Nucleonics ('96 demo) (Japanese bonus track)", trackLength: "3:02"},
                    { trackTitle: "Hedrhoid (Gunt demo) (Japanese bonus track)", trackLength: "1:38"},
                    { trackTitle: "Detox ('96 demo) (Japanese bonus track)", trackLength: "5:48"},
                    { trackTitle: "AAA ('96 demo) (Japanese bonus track)", trackLength: "5:22"},
                ],
            },
            {
                title: "1994-2006 Chaos Years",
                type: "compilation",
                band: "Strapping Young Lad",
                dateRecorded: new Date('2006'),
                dateRelease: new Date('March 31, 2008'),
                studio: "",
                genre: ["",""],
                length: "66:29",
                label: "Century Media",
                producer: "Devin Townsend",
                imgCovername: "1994-2006_Chaos_Years.jpg",
                tracks: [
                    { trackTitle: "S.Y.L.", trackLength: "4:47"},
                    { trackTitle: "In the Rainy Season", trackLength: "4:37"},
                    { trackTitle: "Velvet Kevorkian", trackLength: "1:17"},
                    { trackTitle: "All Hail the New Flesh", trackLength: "5:24"},
                    { trackTitle: "Oh My ******* God", trackLength: "3:34"},
                    { trackTitle: "Detox", trackLength: "5:37"},
                    { trackTitle: "Relentless", trackLength: "3:03"},
                    { trackTitle: "Rape Song", trackLength: "3:09"},
                    { trackTitle: "Aftermath", trackLength: "6:46"},
                    { trackTitle: "Imperial", trackLength: "2:17"},
                    { trackTitle: "Skeksis", trackLength: "6:42"},
                    { trackTitle: "S***storm", trackLength: "4:21"},
                    { trackTitle: "Love?", trackLength: "5:43"},
                    { trackTitle: "You Suck", trackLength: "2:40"},
                    { trackTitle: "Wrong Side", trackLength: "3:35"},
                    { trackTitle: "Almost Again", trackLength: "3:43"},
                    { trackTitle: "Satan's Ice Cream Truck", trackLength: "2:34"},
                ],
            }
        ],
    },
]